[default]
SENTRY_DSN = ""
ALLOWED_HOSTS = ["*"]
DATABASE_URL = "postgresql+asyncpg://ragit_admin:ragit1234@192.168.1.18:5432/ragit"
S3_KEY = "DO00WLJRW9QCARE9ABEZ"
S3_SECRET = "fJdnjgvlgv6xFTxEKJk+8wCiAE9I9ns5p1sMXnayD58"
S3_URI = "https://blr1.digitaloceanspaces.com"
QDRANT_SERVER_URI = "http://192.168.1.18:6333"
REDIS_BROKER = "http://192.168.1.18:6379"