apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragit-api-service-deployment
  labels:
    app: ragit-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ragit-api-service
  template:
    metadata:
      labels:
        app: ragit-api-service
    spec:
      # initContainers:
      # - name: init-redis
      #   image: busybox:1.28
      #   command:
      #     - sh
      #     - -c
      #     - |
      #       until nslookup ragit-api-service-redis.default.svc.cluster.local; do
      #         echo waiting for ragit-api-service-redis; sleep 2;
      #       done;
      containers:
      - name: ragit-api-service
        image: rainmain/ragit-api-service:0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
      - name: ragit-api-service-worker
        image: rainmain/ragit-api-service-worker:0.1
        imagePullPolicy: Always
      - name: ragit-api-service-redis
        image: redis:7.2.4
        imagePullPolicy: Always
        ports:
          - containerPort: 6379
      imagePullSecrets:
        - name: regcred
