apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragit-api-service-redis-deployment
  labels:
    app: ragit-api-service-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ragit-api-service-redis
  template:
    metadata:
      labels:
        app: ragit-api-service-redis
    spec:
      containers:
      - name: ragit-api-service-redis
        image: redis:7.2.4
        imagePullPolicy: Always
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ragit-api-service-redis
  namespace: default
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: ragit-api-service-redis
  type: ClusterIP
